### ISSUE TITLE
RFC: Scoping of Zones

### ISSUE THREAD

**Issue by MathiasPius** [kubi-zone/kubi.zone#1]
Currently the Kubizone Controller and Kubizone Zonefile Controller both work across the entire cluster, which means that even though Zones, DNSRecords and Zonefiles are namespaced, sub-zones and records are "adopted" across namespace boundaries.

This was done because it was the easiest way to get the proof of concept off the ground, but it raises some questions regarding scoping and delegation.

# The problem

The current architecture allows, for example, someone in an otherwise unrelated namespace to "inject" DNSRecords into a zone in an entirely different namespace, simply by setting the `zoneRef` (if they know the resource name and namespace), or the `domainName` of the record to that of the zone.

This poses an egregious risk to multi-tenant clusters, violates the segregation principles of namespaces, and makes the namespaced nature of the Zones, DNSRecords and Zonefiles pointless.

# Solutions

### Limiting scope of Zones, DNSRecords and Zonefiles.

An easy way to resolve the security problems, is to simply limit the scope of Zone and DNSRecord associations to their given namespace. This means that a Zone can only be adopt a sub-zone or record if they are defined within the same namespace.

This approach poses some usability challenges, however. Assuming you have a single Zone for `example.org.` deployed in your `kubizone` namespace, and want to set up a service of some kind to be hosted at `service.example.org.`, you would have to create the DNSRecords for this domain in the `kubizone` namespace, instead of simply deploying it alongside the service itself. 

Breaking locality of the deployment in this way is far from ideal. Especially if the deployed service is managed by people without access to the `kubizone` namespace, which then requires coordination if they want to deploy a new service.

### Mitigating the usability issues by introducing a *delegations* filter to the Zone spec

By allowing the provisioner of the Zone resource to define rules that describe which namespaces are allowed to reference a Zone, you can delegate record creation as loosely as you deem fit. The way I imagine the implementation, would be as a `delegation` field on the Zone manifest, made up of entries defining rules for:
* a set of namespaces
* a set of domain suffixes, and finally
* a set of resources

This is similar to the way Kubernetes Roles are defined.

```yaml
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: example-org
spec:
  domainName: example.org.
  delegations:
  - namespaces:
    - staging
    suffixes: 
    - .staging.example.org.
    resources: 
    - dnsrecords

  - namespaces:
    - customer1
    suffixes: 
    - .customer1.example.org.
    - .customer1.dev.example.org.
    resources:
    - zones
    - dnsrecords

  - suffixes:
    - .sandbox.example.org.
```
This example defines three separate delegations:

1. Applies to the `staging` namespace, and allows any DNSRecords within it matching the `.staging.example.org.` suffix to be adopted by the `example.org.` zone.

2. Applies to to the  `customer1` namespace, and allows any Zone or DNSRecord within the namespace matching *either* `customer1.example.org` or `customer1.dev.example.org` to be adopted by the `example.org.` zone.

3. Does not define resources or namespaces, defaulting to *any*, allowing any Zones and DNSRecords from *any* namespace within the cluster matching the `.sandbox.example.org.` suffix to be adopted.

Assuming *any* poses a risk in accidentally creating too loose a rule by omission.

**Comment by MathiasPius** [comment]
Zones and Records should be delegated independently, and instead of all paths being suffixes, domains should be take the form of some kind f

```yaml
apiVersion: kubi.zone/v1alpha1
kind: Zone
metadata:
  name: example-org
spec:
  domainName: example.org.
  delegations:
  - namespaces:
    - staging
    zones:
    - subzone.staging.example.org.
    dnsrecords:
    - .staging.example.org.
```
